#!/usr/bin/env bash

if
  [[ -s "/user/hongs/.rvm/gems/ruby-1.9.3-p551/environment" ]]
then
  source "/user/hongs/.rvm/gems/ruby-1.9.3-p551/environment"
  exec nokogiri "$@"
else
  echo "ERROR: Missing RVM environment file: '/user/hongs/.rvm/gems/ruby-1.9.3-p551/environment'" >&2
  exit 1
fi
