# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ea8079ae1692dccb4af06058ee07bf44da1c1ec92ceee8cbf4ab8375ada4ac9c8744cbe18b40d5caf55523329d2afa3feef9b4a999836a7611eba46a8436c75

test:
  secret_key_base: 88dff37b4d5bba1a7350ea79ebd0e623a97fe4ca5f1b0c984af89fdf7a0c43aca8ba0118912a38047d5602d2739ca10bd9d7f4187edad2d775e0f7dec9ceb3de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
