#!/usr/bin/env bash

if
  [[ -s "/user/hongs/.rvm/gems/ruby-2.1.1/environment" ]]
then
  source "/user/hongs/.rvm/gems/ruby-2.1.1/environment"
  exec executable-hooks-uninstaller "$@"
else
  echo "ERROR: Missing RVM environment file: '/user/hongs/.rvm/gems/ruby-2.1.1/environment'" >&2
  exit 1
fi
