#!/usr/bin/env bash

if
  [[ -s "/usr/local/rvm/gems/ruby-1.9.3-p545@global/environment" ]]
then
  source "/usr/local/rvm/gems/ruby-1.9.3-p545@global/environment"
  exec bundle "$@"
else
  echo "ERROR: Missing RVM environment file: '/usr/local/rvm/gems/ruby-1.9.3-p545@global/environment'" >&2
  exit 1
fi
