#!/usr/bin/env bash

if
  [[ -s "/user/hongs/.rvm/gems/ruby-2.1.1@global/environment" ]]
then
  source "/user/hongs/.rvm/gems/ruby-2.1.1@global/environment"
  exec testrb "$@"
else
  echo "ERROR: Missing RVM environment file: '/user/hongs/.rvm/gems/ruby-2.1.1@global/environment'" >&2
  exit 1
fi
