#!/usr/bin/env bash

if
  [[ -s "/user/hongs/.rvm/gems/ruby-1.9.3-p551@global/environment" ]]
then
  source "/user/hongs/.rvm/gems/ruby-1.9.3-p551@global/environment"
  exec executable-hooks-uninstaller "$@"
else
  echo "ERROR: Missing RVM environment file: '/user/hongs/.rvm/gems/ruby-1.9.3-p551@global/environment'" >&2
  exit 1
fi
